title: 'Fitness, Strength, and Fat Loss'
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.7225969
favicon: null
name: coachschu
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.4780776
  lightness: 0.3102867
  saturation: 0.5278246
  rhythmicContrast: 0.3246206
  brandColors:
    - '#F1EBE8'
    - '#C6C5BE'
    - '#393B4A'
    - '#657665'
    - '#140F1E'
typography_spectrum: 0.39079
