analytics: {}
color:
  brandColors:
    - '#FBFCFB'
    - '#1F1F30'
    - '#91BDE7'
    - '#654B1F'
    - '#B3891E'
  brandStrength: 0.2158516
  lightness: 0.3102867
  rhythmicContrast: 0.6669477
  saturation: 0.7209106
cta: {}
layout_spectrum: 1
name: coachschu
opengraph: {}
purpose: []
typography_spectrum: 0.8102867
